### ISSUE TITLE
{{#parent-key}}{{child-key}}{{/parent-key}} doesn't work

### ISSUE THREAD

**Issue by cap10morgan** [sunng87/hbs#3]
I'm not sure if this is an hbs issue or a handlebars.java issue, but I would expect both of the templates in [this gist](https://gist.github.com/cap10morgan/03a7c61dfe6f389b4471) to render to the exact same output, but they do not with the current version of hbs.

I tried the same construction with handlebars.js, and it worked there (as well as every other Mustache implementation I've used). Screenshot of the handlebars.js behavior is attached.

![tryhandlebarsjs.com screenshot](https://cloud.githubusercontent.com/assets/59748/6467864/357fc98c-c18e-11e4-9ff8-73a38383b2bc.png)

**Comment by cap10morgan** [comment]
It looks this works in handlebars.java 2.0.0 (running the template server from the JAR file). I'll see if I can try it with 1.3.2 as well.

**Comment by cap10morgan** [comment]
Looks like it works in 1.3.2 also, so I think this is a bug in hbs.

**Comment by cap10morgan** [comment]
As you can see in this [updated gist](https://gist.github.com/cap10morgan/a7df909b1b7f16b8cc39), sending in a Java HashMap makes the bug go away. So it seems the bug may be in `KeywordMapValueResolver.java`?

**Comment by sunng87** [comment]
Thanks for your effort for looking into this issue and making the excellent patch. I have packaged the patch into 0.7.0 and also updated handlebars.java to 2.0.0.
