### ISSUE TITLE
Templates do not reload automatically (includes suggestion)

### ISSUE THREAD

**Issue by mikko-m** [sunng87/hbs#7]
The default behaviour of [ConcurrentMapTemplateCache](https://github.com/jknack/handlebars.java/blob/master/handlebars/src/main/java/com/github/jknack/handlebars/cache/ConcurrentMapTemplateCache.java) that this project uses by default is not to reload automatically. It would be a good idea to either enable reloading by default (as caching map is used) or allow the user to customize reloading on or off via function. 

After browsing code of both this library and handlebars.java this is the code I used to enable the reloading on my program. It would be a good idea to introduce a function similar to set-template-path! to allow setting reloading on or off.

    (.setReload (.getCache handlebars/*hbs*) true))

**Comment by sunng87** [comment]
Thanks for the suggestion. This is pretty handy for development. I will add this feature soon.

**Comment by sunng87** [comment]
released in 0.9.0
