### ISSUE TITLE
Documentation missing for multiparameter helpers

### ISSUE THREAD

**Issue by mikko-m** [sunng87/hbs#8]
I'm trying to use ifcontains and have no clue how it works. There is no documentation of any kind for helpers that have multiple parameters and I think there should be.

This is what I have tried based on guesses on how it could work (roles is a set)

    {{#ifcontains roles :user}}user{{/ifcontains}}
    {{#ifcontains roles item :user}}user{{/ifcontains}}
    {{#ifcontains :user roles}}user{{/ifcontains}}   

All throw an error (a variation of below)

    found: ':user', expected: '}}' <p>User? {{#ifcontains :user roles}}user{{/ifcontains}}

**Comment by mikko-m** [comment]
(test file seemingly contains the correct syntax, it would be a good idea to at least copy test cases as simple examples to documentation)

**Comment by sunng87** [comment]
Thank you for the advice. I will add some text on readme to guide users to find example in test cases.

**Comment by sunng87** [comment]
Closed by 005bee2
