### ISSUE TITLE
Checksum missing

### ISSUE THREAD

**Issue by mikko-m** [sunng87/hbs#9]
I get this error from two separate servers so it doesn't seem to be networking issue.

$ lein ring server-headless

Retrieving hbs/hbs/0.9.1/hbs-0.9.1.pom from clojars
Could not transfer artifact hbs:hbs:pom:0.9.1 from/to clojars (https://clojars.org/repo/): Checksum validation failed, no checksums available from the repository
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.

It seems that checksum is missing. Older version can be installed just fine.

**Comment by sunng87** [comment]
Hi, I can reproduce this issue. Thanks for reporting!
I just uploaded 0.9.2, could you please try again?

**Comment by mikko-m** [comment]
0.9.2 installs fine, thanks for really quick fix!
